/*
 * generated by Xtext
 */
package org.oasisopen;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RelaxngUiModule extends org.oasisopen.AbstractRelaxngUiModule {

}
