/*
 * generated by Xtext
 */
package org.oasisopen;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RelaxngRuntimeModule extends org.oasisopen.AbstractRelaxngRuntimeModule {

}
