/*
* generated by Xtext
*/
package org.oasisopen.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class RelaxngTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
