/*
* generated by Xtext
*/
package org.oasisopen.contentassist;

import org.oasisopen.contentassist.AbstractRelaxngProposalProvider;
/**
 * see http://wiki.eclipse.org/Xtext/Documentation#Content_Assist on how to customize content assistant
 */
public class RelaxngProposalProvider extends AbstractRelaxngProposalProvider {

}
